### ISSUE TITLE
Subpaths isn't handled well

### ISSUE THREAD

**Issue by regebro** [regebro/svg.path#37]
You can have a close command in the middle of a path, which means it's a subpath, and that can be closed, while the path as a whole is open.

This is currently not handled properly. We either need to make that into multiple separate paths, or create a Subpath() object that a Path can contain, but which in turn contains Path commands.

**Comment by tatarize** [comment]
No. There's a third easier option. Add a path element called `Close`.

When a close command is seen in segments it conveys a 'z' command. When you hit a 'z' command add one to the segments.

```
    def closed(self):
        start_pos = self._segments[-1].end
        end_pos = None
        for segment in reversed(self._segments):
            if isinstance(segment, Move):
                end_pos = segment.start
                break
        if end_pos is None:
            end_pos = self._segments[0].start
        self.append(Close(start_pos, end_pos))
```

The close closes to the last Move command per SVG spec.  This is easily the most elegant solution, even though it basically throws a giant wrench in the idea of reversing the paths as you'll need to switch what end of the subpath the Close is on. But, it's certainly doable. Also, it lets you lose the bool `closed` flag which is not elegant.

**Comment by regebro** [comment]
That would require a close command to have to traverse back to the previous Move command, which is doable, but certainly not elegant. I was leaning more towards getting rid of the Move command as well, and use zero length paths for that, but I'm not sure.

**Comment by tatarize** [comment]
In my use case, I have a laser cutter that at the very basic level can only move orthogonal or diagonal 1 stepper motor, x, or y, or both. So I need even discontiguous paths to be contiguous since I need to connect all parts of the graph. I tried getting away with move commands containing the position they were going to, but even that got a bit squirrelly. There is a need for a undrawn line to connect (even in unconnected form) one place with another place and basically that's what move ends up doing. Moving from the current location to the new location.

SVG requires close commands traverse back to the previous move.  You really can't check if you're coincident with the first point of the first element and then draw a line. That's actually bad svg.

If you have a continuous graph with moves that actually connect the two points. When you reverse them, you have still have a move that connects the two points, rather than one that flags the current location before the next discontinuous element.

There are things like the SVG 2.0 spec, where the only thing that really got adopted was alteration to Z as a replacement for a point. You are allowed to do "M x, y L x, y L Z" which actually makes the path Mxy -> Lxy -> LZ where the actual value of Z is the xy point in M.

This makes a closed path with or without that a zero length closing line two different things.

In theory, `Mx0y0 -> Lx1y1 -> LZ`, `Mx0y0 -> Lx1y1 -> Lx0y0` and `Mx0y0 -> Lx1y1 -> Lx1y1Z` are three different graphs.

I've considered things like having flavors of points in a double-linked lists where you could go from anchor point to anchor point and if you do, that's a line, then if you have control points it makes the segment you're in a bezier curve (more control points, higher level curve, in theory with all bezier curves represented; and could have flavors like smooth points which link to other points and reflect).  The benefit being you can bezier curve back to the initial point (another thing the svg 2.0 z permits), without actually deciding that some point is first.

But, really 1:1 svg curve elements and objects like you have seems to be the most understandable and stable. To that end, Move commands and Close commands actually mean something. And adding them to the list is quite nice. Especially because this makes producing the d() text super-easy.

svg.pathtools which is derived code, doesn't have a move command and consequently crashes at if you tell it M0,0z. And if you removed them, then M1,1 L2,2 M00z z might look like coherent svg.

**Comment by regebro** [comment]
Well, the Close command could also have the x,y points to go to, which means you wouldn't have to traverse back, I guess. I'll try to get time to look at that soonish.

**Comment by tatarize** [comment]
It would basically have to, a lot of the code assumes every element has a .start and .end point. So Close would be no different. The code sample I gave up above was to set the values for start and end not to find them arbitrarily on the fly. It would add a Close object that links the current point with the last Move point (or first point in entire path). All in all, it's a pretty small addition that allows subpaths  to exist natively. And it wouldn't be too hard to add a subpath generator. 

```
    def as_subpaths(self):
        last = 0
        subpath = Path()
        for current, seg in enumerate(self):
            if current != last and isinstance(seg, Move):
                subpath._segments = self[last:current]
                yield subpath
                last = current
        subpath._segments = self[last:]
        yield subpath
```

**Comment by tatarize** [comment]
Also, treating `Close` like an object properly makes the offending code in #45 pointless and it can just be removed. It's assuming the last segment in the closed figure is a zero length line and trying to remove it. That kludge in the case of that issue caused it to eat an arc.

**Comment by regebro** [comment]
This is now implemented in #49, if you can take a look at it before I merge it that would be cool.

**Comment by tatarize** [comment]
Seems right. I checked it against my implementation ( https://github.com/meerk40t/meerk40t/blob/master/path.py ) and I can't find a substantive difference between a close or and line. And the code that checks for isinstance seems correctly changed.

**Comment by regebro** [comment]
Cool. Will merge.
