### ISSUE TITLE
Removal of features without warning (Path.closed)

### ISSUE THREAD

**Issue by Silmathoron** [regebro/svg.path#54]
Dear @regebro,
I was very happy to find your library and I am using it in several projects: [NNGT](https://github.com/Silmathoron/NNGT) and [DeNSE](https://github.com/SENeC-Initiative/DeNSE) (as it was an optional dependency it does not appear in the manifest though, so GitHub does not know about it for its dependency graph).

This is just to let you know that, as a dependency published on PyPI, I would expect features such as the ``closed`` property of path to be deprecated before being removed, so as to not break code immediately for everyone who might be using the library.

Am I correct in thinking that this could have been kept using

```python
    @property
    def closed(self):
        return isinstance(self, Close)
```

as an object property?

**Comment by regebro** [comment]
No, it's more complicated than that, but a property like that can be added. It would be read-only, though.

**Comment by Silmathoron** [comment]
That would be fine, thanks for the quick reply.
Indeed, I just noticed that this indeed did not work.
How can I replace the call to ``closed`` right now?

**Comment by regebro** [comment]
Since it now supports subpaths, the concept of a path being closed doesn't really make much sense any more, but I think checking if the last element is `Closed()` should be reasonably backwards compatible. 

How are you using it, and why do you need to know if a path is closed?

**Comment by Silmathoron** [comment]
I'm using it to import SVG images and convert them to Shapely objects (see [function](https://github.com/Silmathoron/PyNCulture/blob/master/svgtools.py#L114)).
Because thee structures are containers, they have to be closed so I check for this.
The code is old though and it may not be the best way to do it, so if you have any suggestions, they would be welcome.

And you meant ``Close``, not ``Closed``, right?

**Comment by regebro** [comment]
I did mean `Close`, yeah.

**Comment by Silmathoron** [comment]
Here is a minimal working example of the issue. There is now a self-crossing in the final figure while the code worked fine with the previous version of svg.path (3.X).
Would you know where the error come from?
[svgpath.zip](https://github.com/regebro/svg.path/files/3943872/svgpath.zip)

**Comment by regebro** [comment]
Wow, that's a lot of subpaths. And one closed subpath is just a MOVE? How can you close a move, you would end up going back to the start?

**Comment by regebro** [comment]
Like this? This is what happens in Inkscape if you remove that Move + Close.

![Screen Shot 2019-12-10 at 10 21 24](https://user-images.githubusercontent.com/820596/70516209-e7d68100-1b36-11ea-89e9-9dce16a44d6f.png)

**Comment by Silmathoron** [comment]
I don't know: the object was made with Inkscape... from what I see on the software, this is a single closed path. I would like to recover this single closed path in Python.

**Comment by regebro** [comment]
Nah, it's a lot of subpaths. I'll have to check if there's an error parsing
it, but I don't have time today.

**Comment by Silmathoron** [comment]
OK, thank you very much for having a look.
I was surprised by the fact that it was parsed correctly in previous versions.
Please keep me updated.

**Comment by Silmathoron** [comment]
@regebro would it be useful for you to have the resulting path from version 3.9, which displayed properly as on the figure above, or does this bring no relevant information?

**Comment by tatarize** [comment]
My svgelements code renders that as:

![svgpath](https://user-images.githubusercontent.com/3302478/71582545-8fecc380-2abf-11ea-9bd7-5c211a4f61e4.png)

"How can you close a move, you would end up going back to the start?" According to the SVG Spec, it's a valid path. And yes, you move then close the move. The only thing that it matters for is that subsequent relative move commands are based on the previous operation so if you merely omitted it, the data would be altered.  

--

He is right that if you install svg.path 3.1 it draws differently even when everything else is the same.

`pip install svg.path==3.1`

**Comment by tatarize** [comment]
Ah, found it. The bug is not in svg.path it's in svgtools line 141 should read:

`if isinstance(item, Close) and j < len(path_data) - 1:`

Currently it's cheating in a methodology that doesn't actually work if the code is done correctly.

`if item.end == start and j != idx_start and j < len(path_data) - 1:`

The bug here is he's checking for pseudo-close commands. Namely the zero length lines which start and end at the position of the start. Properly Z commands can have length and should. They actually end at the position of the Move's destination. A move does not necessarily have a start position. This code would have worked in 3.1 because produced exactly the right type of garbage for this code to match and used to determine there could have been a z used there. It's depending on the kludges in 3.1 to interpret Z commands even when they denote multi-paths. When Rege fixed those kludges with proper code, it broke this code which depended on them.

You could also cheat and do 'M0,0 L 3,3 L3,0 L0,0 h0 L 5,0 z' and it would wrongly take that h0 to be a z because it's zero length and located at M0,0 so it looks like the code 3.1 would have made.

Note, my change there makes lines: 123, 130, 144, 145 unneeded. In fact, you can rewrite that properly to append the current points value to holes when it sees a Close and simply the whole block pretty nicely.

**Comment by tatarize** [comment]
Even if Regebro had given an object property to do figure out of older code would have returned True or False for closed. (By the way the correct code isn't to check the last segment but rather to check if a close command is anywhere in the entire path, because that's what would trigger that setting in 3.1.) This code actually is depending on the fact that 3.1 would make kind of pointless lineto, that was somewhat out of spec. Even with the object property this woulda failed.

**Comment by tatarize** [comment]
https://xkcd.com/1172/

**Comment by Silmathoron** [comment]
@tatarize nice! thanks a lot for looking into this :)
I did not work on that part of the code and figuring this out would have taken me forever.

**Comment by tatarize** [comment]
`Close` works like Z. It closes a path in the same fashion Z does. Which is, according to the spec to draw a line from the current position to the Z point, which was the previous move command.

I'd need to see the code for that bit to see what went wrong. But, it likely isn't close. That last part of the shape is clearly part of an arc-to and is absent. My guess is that it's actually deleting the last segment manually because in the older version it would have been a zero point line. However, this version doesn't do that makeshift pathing and rather the last segment is the arc to.

**Comment by tatarize** [comment]
I'd need the svg to confirm but it seems like the inverse problem of #45 where an arc was being dropped by the code because close caused zero point lines. I'd figure the code here is *also* doing a version of that. And when it was fixed in svg.path and the last segment drop code was removed (as unneeded), your version actually had it's own version of that same drop code. And is actually invoking it. So rather than pluck off the pointless segment it's plucking off the last arc.

**Comment by tatarize** [comment]
> just to make sure, though, the Close object which determines whether the object is closed in a polygon with holes has to be the last one, right?

No. Each subpath where the line is moved must be itself closed with a Close object. The difference between those two shapes is that the latter is that one contains an Arc-to and a Close in one subpath and the other one does not.

**Comment by tatarize** [comment]
M 1,0 A 1,1 0 0,0 0,-1 A 1,1 0 0,0 -1,0 A 1,1 0 0,0 0,1  M 2,0 A 2,2 0 0,1 0,2 A 2,2 0 0,1 -2,0 A 2,2 0 0,1 0,-2 A 2,2 0 0,1 2,0 Z
vs.
M 1,0 A 1,1 0 0,0 0,-1 A 1,1 0 0,0 -1,0 A 1,1 0 0,0 0,1 A 1,1 0 0,0 1,0 Z M 2,0 A 2,2 0 0,1 0,2 A 2,2 0 0,1 -2,0 A 2,2 0 0,1 0,-2 A 2,2 0 0,1 2,0 Z

To make it clear I removed "A 1,1 0 0,0 1,0 Z" from the end of the first subpath which is for the hole. The distinction between your two shapes is that one shape is missing an arc and a close command.

![shape1](https://user-images.githubusercontent.com/3302478/71648547-8ed3b600-2cba-11ea-83a7-cb8d5dd2c546.png)

To figure out that these are closed you'd iterate the segment list and check that each subpath, all of which start with an M (Move)) end with a Z (Close).

**Comment by tatarize** [comment]
Here's some functions to make the code easier if you want:


```
from svg.path import Move, Close, Path

def get_subpaths(path):
    segments = None
    for p in path:
        if isinstance(p, Move):
            if segments is not None:
                raise RuntimeError("Only closed shapes accepted.")
            segments = []
        segments.append(p)
        if isinstance(p, Close):
            yield Path(*segments)
            segments = None


def get_points(path, interpolate_curve=50):
    points = []
    for item in path:
        if isinstance(item, (Arc, CubicBezier, QuadraticBezier)):
            istart = 1. / interpolate_curve
            for frac in np.linspace(istart, 1, interpolate_curve):
                points.append(
                    (item.point(frac).real, item.point(frac).imag))
        else:
            points.append((item.start.real, item.start.imag))
    return points
```

Which could use the start code block:
```
        path_data = parse_path(instructions["path"])
        subpaths = [subpath for subpath in get_subpaths(path_data)]
        shell = get_points(subpaths[0], interpolate_curve)  # the first path is the outer shell?
        holes = [get_points(subpath) for subpath in subpaths[1:]]
        shell = np.array(shell)
        container = Polygon(shell, holes=holes)
```

**Comment by tatarize** [comment]
You'll note I have the get_subpaths() code throw an error if *any* subpath is not closed.

**Comment by Silmathoron** [comment]
@tatarize it all works, thank you very much for the help.

@regebro depending on whether or not you want to reimplement `closed` (which I still think should be a good idea, e.g. as proposed in @tatarize's code), feel free to close this issue

**Comment by tatarize** [comment]
My recommended code for a `closed` property is:

```python
    def subpaths(self):
        segments = None
        for p in self._segments:
            if isinstance(p, Move):
                if segments is not None:
                    yield Path(*segments)
                segments = []
            segments.append(p)
            if isinstance(p, Close):
                yield Path(*segments)
                segments = None
        if segments is not None:
            yield Path(*segments)

    @property
    def closed(self):
        """        
        Deprecated. This is legacy support code for svg.path < 4.0.
        
        :return boolean of whether any path is closed.
        """
        for subpath in self.subpaths():
            if isinstance(subpath[-1], Close):
                return True
        return False
```

This properly duplicates the functionality of the old form, which would be closed if it ever saw a close command anywhere. This would also add a subpaths() helper function that could be made private, but is something people will sort of need. Though my recommendation would be to only add subpaths() and let the closed property die. 

Also, @Silmathoron, my code for get_subpaths() to you should have ended with:
```python
        if segments is not None:
            raise RuntimeError("Only closed shapes accepted.")
```

Since the last path being unclosed will fall out of the loop, not returning the unclosed path, or throwing an error. This wouldn't break anything, but it seemed like throwing the error was a wanted event.

Also, if you'd be going all in on that legacy support:

```python
    @closed.setter
    def closed(self, close):
        """
        Deprecated. This is legacy support code for svg.path < 4.0.
        """
        if close:
            try:
                start = self._segments[-1].end
            except IndexError:
                return
            end = None
            for i in range(len(self._segments) - 1, -1, -1):
                seg = self._segments[i]
                if isinstance(seg, Move):
                    end = seg.end
                    break
            if end is not None:
                self.append(Close(start, end))
        else:
            self._segments = [s for s in self._segments if not isinstance(s, Close)]
```

Though I didn't check this. Setting closed to True appends a Close to the end of the path. Setting closed to False, strips all Close commands from the segments. The close command is a bit odd there but it's how they need to work. In `svgelements` I do that stuff automatically since it does integrity checks all added and inserted and appended items.

**Comment by tatarize** [comment]
@regebro if you're on a closing spree... this thing seems entirely settled.

**Comment by regebro** [comment]
True. No point in reintroducing `closed` now. Thanks!
