### ISSUE TITLE
Convert arc and quadratic bezier to cubic bezier

### ISSUE THREAD

**Issue by mazznoer** [regebro/svg.path#59]
In `Path`, how to convert `Arc` and `QuadraticBezier` to `CubicBezier`. Maybe it is nice to add option to do something like that.

Sorry for my broken english.

**Comment by regebro** [comment]
I guess that would be a nice feature in a svg transform package.

**Comment by tatarize** [comment]
My `svgelements` ( https://github.com/meerk40t/svgelements) module isn't specifically intended towards shape transformations but it has those commands. There are a lot of graphic applications that do not provide arcs and you do need to subdivide them into things it can use while my intent on my project is more to parse nearly perfect svg with all the css and various other things using `svg.path` as the original base. It's entirely the case the this stuff comes up enough to meaningfully consider this even without other functions like interpret a bezier curve as an arc-like objects (see: https://pomax.github.io/bezierinfo/#arcapproximation ).

```python
    def as_quad_curves(self):
        sweep_limit = tau / 12
        arc_required = int(ceil(abs(self.sweep) / sweep_limit))
        if arc_required == 0:
            return
        slice = self.sweep / float(arc_required)

        current_t = self.get_start_t()
        p_start = self.start

        theta = self.get_rotation()
        cos_theta = cos(theta)
        sin_theta = sin(theta)

        a = self.rx
        b = self.ry
        cx = self.center[0]
        cy = self.center[1]

        for i in range(0, arc_required):
            next_t = current_t + slice
            mid_t = (next_t + current_t) / 2
            p_end = self.point_at_t(next_t)
            if i == arc_required - 1:
                p_end = self.end
            cos_mid_t = cos(mid_t)
            sin_mid_t = sin(mid_t)
            alpha = (4.0 - cos(slice)) / 3.0
            px = cx + alpha * (a * cos_mid_t * cos_theta - b * sin_mid_t * sin_theta)
            py = cy + alpha * (a * cos_mid_t * sin_theta + b * sin_mid_t * cos_theta)
            yield QuadraticBezier(p_start, (px, py), p_end)
            p_start = p_end
            current_t = next_t

```

And the cubic curves code.

```python

    def as_cubic_curves(self):
        sweep_limit = tau / 12
        arc_required = int(ceil(abs(self.sweep) / sweep_limit))
        if arc_required == 0:
            return
        slice = self.sweep / float(arc_required)

        theta = self.get_rotation()
        rx = self.rx
        ry = self.ry
        p_start = self.start
        current_t = self.get_start_t()
        x0 = self.center[0]
        y0 = self.center[1]
        cos_theta = cos(theta)
        sin_theta = sin(theta)

        for i in range(0, arc_required):
            next_t = current_t + slice

            alpha = sin(slice) * (sqrt(4 + 3 * pow(tan((slice) / 2.0), 2)) - 1) / 3.0

            cos_start_t = cos(current_t)
            sin_start_t = sin(current_t)

            ePrimen1x = -rx * cos_theta * sin_start_t - ry * sin_theta * cos_start_t
            ePrimen1y = -rx * sin_theta * sin_start_t + ry * cos_theta * cos_start_t

            cos_end_t = cos(next_t)
            sin_end_t = sin(next_t)

            p2En2x = x0 + rx * cos_end_t * cos_theta - ry * sin_end_t * sin_theta
            p2En2y = y0 + rx * cos_end_t * sin_theta + ry * sin_end_t * cos_theta
            p_end = (p2En2x, p2En2y)
            if i == arc_required - 1:
                p_end = self.end

            ePrimen2x = -rx * cos_theta * sin_end_t - ry * sin_theta * cos_end_t
            ePrimen2y = -rx * sin_theta * sin_end_t + ry * cos_theta * cos_end_t

            p_c1 = (p_start[0] + alpha * ePrimen1x, p_start[1] + alpha * ePrimen1y)
            p_c2 = (p_end[0] - alpha * ePrimen2x, p_end[1] - alpha * ePrimen2y)

            yield CubicBezier(p_start, p_c1, p_c2, p_end)
            p_start = Point(p_end)
            current_t = next_t
```

Since all my code tends to be backwards compatible with svg.path it should be fairly close. You might need p_start and p_end to call .imag and .real for paths code. And I think there might be some small quirks with t vs angle stuff with paths. But the code isn't that hard and it can be simply put into a generator to spit out the needed objects.

**Comment by piscvau** [comment]
Hello I desperately need a function to approximate an SVG arc with a set of Bezier curves. This is for a knitting application. I was willing to help bring this to the community, and I did a fork with the intention to take the as_quad curves code of tatarize and make it a method for the arc class of this svg path. Do you believe this is a right approach? 
I have another question about how to proceed to have a visual check that the approximation is correct. Would drawing into Cairo would be a right approach and if so how to integrate the code in the repository.
Please be indulgent if my questions are basic, I am not an experienced contributor to open source projects nor with svg..

**Comment by piscvau** [comment]
Hello ,in fact I made a mistake and it is Cubic Bezier Curves that I need. SO the code above is not appropriate. Do you have any suggestion on how to approximate the arc with Bezier cubic cuves?  Any suggestion would be welcomed.

**Comment by tatarize** [comment]
https://github.com/meerk40t/svgelements/blob/master/svgelements/svgelements.py#L4147

It should read basically verbatim. The only bug it had was in a different routine dealing with the difference between rotation and t vs. angle, since the math there got screwy at a weird edge condition where it exceeded 3/4th tau. But that didn't affect this bit of code.

**Comment by piscvau** [comment]
Hello tatarize, 
I am trying hard but svgelements has so many functions that it is hard for an incompetent person  like me to figure out the relationships between your Arc attributes and regebro's arc attributes. 
Here https://github.com/piscvau/svg.path/tree/master/src/svg/path I have subclassed the arc and cubic classes from regebro. to add the as_cubic_curves and some draw function to compare the cubic beziers with the original arc.
 However, I cannot figure out how I should set the sweep value in as_cubic_curves,. Obviously, self.sweep in regebro's is a boolean and yours is different, it seems to be an angle!...
If you can provide some help I would really appreciate it!...

**Comment by tatarize** [comment]
That's fair. The Arc class has a bunch of different stuff that is kind of hard keep correct add to that the fact my arcs need to transform with matrices etc, and there's not much left. The easiest thing would be to just understand the posted code there. Since the code there is tightly tied with other code.

The needed parameters are `sweep`, that's the amount around the arc we are travelling in radians. The `rotation` is the amount the underlying ellipse would be rotated by. The `start_t` value is the t value of the start position. Note that ellipses have two parameters they can have these are largely `angle` and `t`. In a circular arc these are the same thing. In an ellipse the `t` value is the amount through the shape, it shares some relationship with angle but becomes a bit obvious if you consider a completely flat ellipse. Where ry is 0. Angle basically becomes meaningless but `t` means what angle would mean if it were a circular arc.  `rx` and `ry` are the radius x and radius y values of the underlying ellipse. The `center` is the center of the ellipse. A lot of these have fairly direct connections with regebro's Arc. The rest of the code is simply taking slices of the arc in tau/12 sections and solving for the closest matching CubicBezier bezier code.  The math there would be explained (http://www.spaceroots.org/documents/ellipse/elliptical-arc.pdf on pages 15-18). It's basically solving for an alpha value that lets you then calculate the control points that closely approximate the arc. Really it's just converting some range of `t` within a defined ellipse. Where the ellipse is defined by `rx`, `ry`, `center` and `theta`. Which should be pretty directly parallel with regbro's code.

**Comment by tatarize** [comment]
Your code isn't too bad, though it sort of misses sweep by a bit. Arc can be seen like they exist on an ellipse. Sweep is the amount of rotation in `t` that goes from start to end. It's not strictly `end - start`. Regebro's code actually has this but it's hidden, it's actually under `self.delta` and is solved in the parameterization of the svg.

Since the svgelements code needs to do math it actually solves all these things. Admittedly, the Arc code alone is longer than the entire code base of svg.path. Literally 700+ vs 500+ lines.

**Comment by piscvau** [comment]
Thank you verymuch  for the comments which kind of got me out of my desperate state!... Also I just came across this morning with the spaceroots document  which helps a lot!...The spaceroot website was unavailable most of last week and so I had no chance to get the maths basis from your code!...
I also wandered around the svgpathtools this morning and I saw there are more transform functions in this package. would it make more sense to add the as_cubic curves into this package?

**Comment by piscvau** [comment]
Also I looked into the JS library https://github.com/fontello/svgpath/blob/master/lib/a2c.js and here they seem to use a different method to approximate to cubic Bezier curve. They use a bezier approximation of a unit circle which they map afterward to the ellipse. Which method is the preferred one?

**Comment by tatarize** [comment]
The math should work the same. The conversion between a unit circle and an ellipse is a mapped matrix. You can represent *all* ellipses as smeared unit circles manipulated by a matrix. I looked into using that as my underlying parameterization since it would natively allow matrix manipulations. I'd need sweep and a matrix and know that the matrix applies to a unit circle. I had change the internal parameterization for the arc because I needed to do matrix manipulations to fully encapsulate the svg spec. I opted to run it as being represented by 5 points that I could transform with a matrix. I think the unit circle math got a bit unruly when I did an in depth analysis. I couldn't just state the start and end points directly, I would need to calculate them and consequently calculate the inverse matrix to map them back and determine the sweep amount. The SVG package gave me the start and end points, and a couple parameters but mapping that to the unit circle requires solving something that was much more unruly. My code currently takes the start and end points as actual points. And adds to them an `rx` point and `ry` point and a `center` point. I calculate the `rotation` by the angle between the `center` and `rx` point and the `rx` and `ry` by the distance between `rx` and `center` and distance between `ry` and store the sweep directly.

I very much like `svgpathtools`, and have contributed to it repeatedly. It has better math and some of the `svgelements` code is pulled from `svgpathtools` specifically figuring out tighter bounding boxes for arc, and some bezier curves. I still don't understand the arc code fully. 

If you wanted to hack it in, you could just use the svgelements code. Just import it as something else, and make an arc. And convert that arc to bezier curves. And then be done with it. Since it's kind of intended to allow such things.

**Comment by tatarize** [comment]
Okay. Done.  And correctly ported it over for you.

I went back and checked and did dual-debugging. Where I debug both functions at once and make sure all the parts equal. I was wrong about what svg.path arc.theta meant. It's actually properly start_t position. Here's the corrected svg.path compatible code, since the math background is certainly too high to correctly count my answer as satisfactory.

```python
    def as_cubic_curves(self, arcs=1):
        slice_t = radians(self.delta) / float(arcs)

        current_t = radians(self.theta)
        rx = self.radius.real * self.radius_scale
        ry = self.radius.imag * self.radius_scale
        p_start = self.start

        theta = radians(self.rotation)
        x0 = self.center.real
        y0 = self.center.imag
        cos_theta = cos(theta)
        sin_theta = sin(theta)

        for i in range(0, arcs):
            next_t = current_t + slice_t

            alpha = sin(slice_t) * (sqrt(4 + 3 * pow(tan((slice_t) / 2.0), 2)) - 1) / 3.0

            cos_start_t = cos(current_t)
            sin_start_t = sin(current_t)

            ePrimen1x = -rx * cos_theta * sin_start_t - ry * sin_theta * cos_start_t
            ePrimen1y = -rx * sin_theta * sin_start_t + ry * cos_theta * cos_start_t

            cos_end_t = cos(next_t)
            sin_end_t = sin(next_t)

            p2En2x = x0 + rx * cos_end_t * cos_theta - ry * sin_end_t * sin_theta
            p2En2y = y0 + rx * cos_end_t * sin_theta + ry * sin_end_t * cos_theta
            p_end = p2En2x + p2En2y * 1j
            if i == arcs - 1:
                p_end = self.end

            ePrimen2x = -rx * cos_theta * sin_end_t - ry * sin_theta * cos_end_t
            ePrimen2y = -rx * sin_theta * sin_end_t + ry * cos_theta * cos_end_t

            p_c1 = (p_start.real + alpha * ePrimen1x) + (p_start.imag + alpha * ePrimen1y) * 1j
            p_c2 = (p_end.real - alpha * ePrimen2x) + (p_end.imag - alpha * ePrimen2y) * 1j

            yield CubicBezier(p_start, p_c1, p_c2, p_end)
            p_start = p_end
            current_t = next_t
```

Just paste this into svg.path `Arc` routine, and add tan to the math imports at the top and you're done.

I'd make a pull since @regebro might add it, though it seems like quad would also need porting in a pull, but I already have a pull pending for merging the parser with the path. That I genuinely think is highly helpful and doesn't break anything. And it would also need to quad code correctly ported over.

**Comment by tatarize** [comment]
Here's the quad code:

```python
    def as_quad_curves(self, curves=1):
        slice_t = radians(self.delta) / float(curves)

        current_t = radians(self.theta)
        a = self.radius.real * self.radius_scale
        b = self.radius.imag * self.radius_scale
        p_start = self.start

        theta = radians(self.rotation)
        cx = self.center.real
        cy = self.center.imag

        cos_theta = cos(theta)
        sin_theta = sin(theta)

        for i in range(curves):
            next_t = current_t + slice_t
            mid_t = (next_t + current_t) / 2
            cos_end_t = cos(next_t)
            sin_end_t = sin(next_t)
            p2En2x = cx + a * cos_end_t * cos_theta - b * sin_end_t * sin_theta
            p2En2y = cy + a * cos_end_t * sin_theta + b * sin_end_t * cos_theta
            p_end = p2En2x + p2En2y * 1j
            if i == curves - 1:
                p_end = self.end
            cos_mid_t = cos(mid_t)
            sin_mid_t = sin(mid_t)
            alpha = (4.0 - cos(slice_t)) / 3.0
            px = cx + alpha * (a * cos_mid_t * cos_theta - b * sin_mid_t * sin_theta)
            py = cy + alpha * (a * cos_mid_t * sin_theta + b * sin_mid_t * cos_theta)
            yield QuadraticBezier(p_start, px + py * 1j, p_end)
            p_start = p_end
            current_t = next_t
```

**Comment by piscvau** [comment]
Also I looked into the JS library https://github.com/fontello/svgpath/blob/master/lib/a2c.js and here they seem to use a different method to approximate to cubic Bezier curve. They use a bezier approximation of a unit circle which they map afterward to the ellipse. Which method is the preferred one?

**Comment by tatarize** [comment]
Since this is svg the current method that I posted code for is preferred. The distinction is that unit circle works but you have to map the start and end point correctly and that's trivial. I tried it, but it got pretty unruly. And I already have this code working with all the quirks. And there are a lot of quirks that you could get wrong with these approximations.

**Comment by regebro** [comment]
This is out of scope for svg.path.
