### ISSUE TITLE
length() fails on certain quadratic curves

### ISSUE THREAD

**Issue by martinleopold** [regebro/svg.path#61]
I'm doing interpolation on a large dataset of paths and came across two cases of quadratic curves where calling `length()` (or `point()`) will throw an exception. Here are some minimal examples:

```python
    from svg.path import parse_path
    p = parse_path('M 206.5,525 Q 162.5,583 162.5,583')
    print( p.length() )
    # ZeroDivisionError: float division by zero
    # File "/Users/mlg/code/ldb-modules-py/venv/ldb-modules-py/lib/python3.7/site-packages/svg/path/path.py", line 203, in length
    # + (4 * C * A - B ** 2) * log((2 * A2 + BA + Sabc) / (BA + C2))
    # -> (BA + C2) == 0.0
```
```python
    from svg.path import parse_path
    p = parse_path('M 880,54.0571 Q 929,101.057 929,101.057')
    print( p.length() )
    # ValueError: math domain error
    # File "/Users/mlg/code/ldb-modules-py/venv/ldb-modules-py/lib/python3.7/site-packages/svg/path/path.py", line 191, in length
    # Sabc = 2 * sqrt(A + B + C)
    # -> A+B+C == -3.637978807091713e-12 (< 0)
```

I don't understand the algorithm thoroughly but it seems both errors vanish when using a larger value for the epsilon term (currently 1e-12).

**Comment by martinleopold** [comment]
Here are some more edge cases I found recently. They all produce very small triangles (between start, control, end points), but valid curves nonetheless:

```
M 425.781 446.289 Q 410.40000000000003 373.047 410.4 373.047
area: -4.1633256842032985e-12

M 639.648 568.115 Q 606.6890000000001 507.568 606.689 507.568
area: -6.883396963530689e-12

M 288.818 616.699 Q 301.025 547.3629999999999 301.025 547.363
area: 1.3877752280677662e-12

M 339.927 706.25 Q 243.92700000000002 806.25 243.927 806.25
area: 2.8421709430404007e-12

M 539.795 702.637 Q 548.0959999999999 803.4669999999999 548.096 803.467
area: -1.051932940754341e-11

M 537.815 555.042 Q 570.1680000000001 499.1600000000001 570.168 499.16
area: -8.192102995963067e-12

M 615.297 470.503 Q 538.797 694.5029999999999 538.797 694.503
area: -8.697043085703626e-12
```

**Comment by tatarize** [comment]
Yeah, the problem is where that is checked the error is checked against being less than 1e-12 you have examples where the degree area is greater than that error but still BA + C2 = 0. Which causes the divide by zero error.  The problem is those values use a bunch of squares and logs and such and thus have an error greater than 1e-12. 

Rather than do what's done in the original code, or what's done in your code in #62 what you need to do is just do that block of code first. Then catch any divide by zero errors or value error (domain) and use those as an indication that these are either three coincident points (the first check) or they are collinear points (the second check)

```python
    def length(self, error=None, min_depth=None):
        """Calculate the length of the path up to a certain position"""
        a = self.start - 2 * self.control + self.end
        b = 2 * (self.control - self.start)
        try:
            # For an explanation of this case, see
            # http://www.malczak.info/blog/quadratic-bezier-curve-length/
            A = 4 * (a.real ** 2 + a.imag ** 2)
            B = 4 * (a.real * b.real + a.imag * b.imag)
            C = b.real ** 2 + b.imag ** 2

            Sabc = 2 * sqrt(A + B + C)
            A2 = sqrt(A)
            A32 = 2 * A * A2
            C2 = 2 * sqrt(C)
            BA = B / A2

            s = (A32 * Sabc + A2 * B * (Sabc - C2) + (4 * C * A - B ** 2) *
                 log((2 * A2 + BA + Sabc) / (BA + C2))) / (4 * A32)
        except (ZeroDivisionError, ValueError):
            # a_dot_b = a.real * b.real + a.imag * b.imag
            if abs(a) < 1e-10:
                s = abs(b)
            else:
                k = abs(b) / abs(a)
                if k >= 2:
                    s = abs(b) - abs(a)
                else:
                    s = abs(a) * (k ** 2 / 2 - k + 1)
        return s
```

That should actually fix the problem. If you hit an error, then you know your code is one of those things you would have otherwise checked for. So go ahead and assume they are true. We can do that now without the checks since BA + C2 being equal to zero (or so low it made the other values infinite) basically does that check for us.

Then we add in a solid test, this should be placed in test_paths.py, QuadraticBezierTest:

```python
    def test_issue_61(self):
        p = Path('M 206.5,525 Q 162.5,583 162.5,583')
        self.assertAlmostEqual(p.length(), 72.80109889280519)
        p = Path('M 425.781 446.289 Q 410.40000000000003 373.047 410.4 373.047')
        self.assertAlmostEqual(p.length(), 74.83959997888816)
        p = Path('M 639.648 568.115 Q 606.6890000000001 507.568 606.689 507.568')
        self.assertAlmostEqual(p.length(), 68.93645544992873)
        p = Path('M 288.818 616.699 Q 301.025 547.3629999999999 301.025 547.363')
        self.assertAlmostEqual(p.length(), 70.40235610403947)
        p = Path('M 339.927 706.25 Q 243.92700000000002 806.25 243.927 806.25')
        self.assertAlmostEqual(p.length(), 138.6217876093077)
        p = Path('M 539.795 702.637 Q 548.0959999999999 803.4669999999999 548.096 803.467')
        self.assertAlmostEqual(p.length(), 101.17111989594662)
        p = Path('M 537.815 555.042 Q 570.1680000000001 499.1600000000001 570.168 499.16')
        self.assertAlmostEqual(p.length(), 64.57177814649368)
        p = Path('M 615.297 470.503 Q 538.797 694.5029999999999 538.797 694.503')
        self.assertAlmostEqual(p.length(), 236.70287281737836)
```

I did the first path sum correctly because I could but the rest of these since they end up in inexact fallback code should be solved for their correct length independently.  I just used the result they gave.

There might also be a case of coincident points that are just outside the range like the edge cases you found here.

Oh, and change the Path() there in the text case to parse_path(), my code in `svgelements` allows that initialization but svg.paths here doesn't.

**Comment by regebro** [comment]
Yeah, tatarize's method is better, because essentially, the code checks for too small values here already, but  1e-12 was too small, and one of the tests added actually has abs(a) being 1.8e-12 causing an error.

So by not checking and letting the code fail, we *know* it's too small, and testing with 1e-10 is fine.
