### ISSUE TITLE
Switch to PEP 420 namespace packages

### ISSUE THREAD

**Issue by jaraco** [regebro/svg.path#67]
In jaraco/svg.charts#27, I'm pondering changing the namespace from a pkgutil-style namespace to PEP 420 native namespace packages. Such a change would break version compatibility if both this and svg.charts were installed together, so I'd like to synchronize the migration. Additionally, such a change can only happen after dropping Python 3.2 and earlier, so is blocked on #55 

I acknowledge it's not been but a couple of years since #41, so I apologize for the flux. Let me know when you would feel comfortable making this (somewhat backward-incompatible) change.

**Comment by tatarize** [comment]
Yeah, I was busy integrating https://github.com/meerk40t/svgelements into https://github.com/vlachoudis/bCNC since I do highly robust svg parsing and the dot I had in the name at the time was a total pain in the butt. I tried a few things to get it to work, but I eventually decided to go with the PEP that said you shouldn't have a dot in your name. I renamed the project and moved to `1.x.x` from `0.x.x`, and released a version that begged people to switch over in the readme (https://pypi.org/project/svg.elements/) though this would cause way less trouble since not many folks used my project at the time. It's really hard to import the package when there's a dot in the name because it treats those like directories, so you make some fake directories with specialty `init.py` and it's still a huge pain.

I would recommend @regebro just co-publish the project if he wants to maintain `svg.path` as it currently stands. So he'd just have a duplicate project at `svgpath` and this code wouldn't be breaking, but future code could use the latter bits. 

I can email the guy who currently has https://pypi.org/project/svgpath/ right now, since his "project" is just something that says you should use regbro's project, and see what the logistics are there.

I would highly endorse this since I already did to the point of moving my project.

**Comment by tatarize** [comment]
I sent william.bengtson an email to maybe show up here. At a minimum @regebro should take over the svgpath name and upload the same code here. Which is mostly just logistics, but wouldn't commit to any breaking changes since nothing here would change, he'd just have the project mirrored at the name that conforms to PEP 420.

**Comment by jaraco** [comment]
To be clear - I would prefer to maintain an `svg` namespace. It's a good form of encapsulation and the only strategy that works long-term. Although `.` is discouraged for non-namespace packages, it _is_ the form for namespace packages. I'm sorry you were burned by them. I'm personally heavily invested in them, and have several namespaces (jaraco, pmxbot, backports, yg, zc) that I own or share ownership. I'm very much interested in working through the (presumably final) transition to PEP 420 namespace packages for the `svg` namespace. Although it will have some compatibility concerns, this final transition represents a long, hard fought effort for Python to provide robust namespaces like other mature languages (e.g. Java) do. I think it would be as shame for svg.path to separately expose `svgpath` or to abandon `svg` altogether due to this issue. I'm committed to taking whatever steps are necessary to limit the blast radius of this transition such that the user impact is minimized, even if that means a multi-year transition.

**Comment by tatarize** [comment]
Yeah, philosophy aside, it would be better of regebro took over svgpath even if he only left the current stub there remaining there. Python seemed to throw up some roadblocks when I tried to use it. Figured I was better off using something I could get to work consistently.

**Comment by jaraco** [comment]
On further consideration, I've run some tests and confirmed that pkgutil-style namespaces and PEP 420 packages seem to be interoperable, even if one or more of the packages are installed editable. Between that and the limited interaction between these packages, I don't believe there's any need to coordinate the transition to PEP 420 namespace packages, so I'll close this request, though I welcome the transition at any point.
